name: Test ./letterboxd_list module

on:
  push:
    branches: [ "main", "testing" ]
  pull_request:
    branches: [ "main" ]

jobs:
  windows_test:

    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pip
      run: py -m pip install --upgrade pip
    - name: Install module and testing dependencies
      run: py -m pip install --upgrade .\letterboxd_list[testing]
    - name: Test module
      run: |
        New-Item -ItemType Directory imadir
        py -m pytest --cov --cov-report term-missing